services:
  jekyll:
    build: .
    image: wuj-github-io-jekyll
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - bundle:/usr/local/bundle
    environment:
      JEKYLL_ENV: development

volumes:
  bundle:
